id: 1ea866caa29944acaa89bfc212db096e
initial_creation_type: ocr
source_metadata:
  volumes:
    befe9c96e62742b3b7cc477e09454556:
      base_file: v001.txt
      image_group_id: I1PD95846
      title: སྐུ་གསུམ་ལ་བསྟོད་པ།
      total_pages: 1539
      volume_number: 1
